# Generated by Django 2.2.6 on 2019-10-28 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TB_Cachorro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_c', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=500)),
                ('raca', models.CharField(max_length=100)),
                ('local', models.CharField(max_length=100)),
                ('sexo', models.CharField(max_length=1)),
                ('recompensa', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TB_Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
                ('telefone', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=60)),
                ('senha', models.CharField(max_length=100)),
            ],
        ),
    ]
